package sdkwrapper.vo.transaction;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BlockTransaction
{
  private long    blockSeqNum    = 0;     // Block Seq Number transaction in.
  private String  tranType       = null;
  private String  transactionId  = null;  // Unique transaction Id generated by SDK
  private Date    tranTimestamp  = null;
  private long    epoch          = 0;
  private boolean isValid        = false; // Transaction Successful or Failed
  private String  validationCode = null; 

  private List<BlockTransactionAction> tranActions = new ArrayList<BlockTransactionAction>();
  
  public long    getBlockSeqNum()    { return blockSeqNum;    }
  public String  getTranType()       { return tranType;       }
  public String  getTransactionId()  { return transactionId;  }
  public Date    getTranTimestamp()  { return tranTimestamp;  }
  public long    getEpoch()          { return epoch;          }
  public boolean isValid()           { return isValid;        }
  public String  getValidationCode() { return validationCode; }
  
  public List<BlockTransactionAction> getTranActions() { return tranActions; };
   
  public void setBlockSeqNum(    long    blockSeqNum ) { this.blockSeqNum    = blockSeqNum; }
  public void setTranType(       String  tranType    ) { this.tranType       = tranType;    }
  public void setTransactionId(  String  tranId      ) { this.transactionId  = tranId;      }
  public void setTranTimestamp(  Date    timestamp   ) { this.tranTimestamp  = timestamp;   }
  public void setEpoch(          long    epoch       ) { this.epoch          = epoch;       }
  public void setValid(          boolean isValid     ) { this.isValid        = isValid;     }
  public void setValidationCode( String code         ) { this.validationCode = code;        }
}
